// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Perfumes.Api.Data;

#nullable disable

namespace Perfumes.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Perfumes.Api.Entities.Fornecedor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CpfCnpj")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Site")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CpfCnpj")
                        .IsUnique()
                        .HasFilter("[CpfCnpj] IS NOT NULL");

                    b.HasIndex("RazaoSocial");

                    b.ToTable("Fornecedores", (string)null);
                });

            modelBuilder.Entity("Perfumes.Api.Entities.FornecedorProduto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoProdutoFornecedor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("FornecedorId")
                        .HasColumnType("bigint");

                    b.Property<long>("InsumoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("QuantidadeBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("QuantidadeEmbalagem")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("UnidadeBase")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeEmbalagem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId");

                    b.HasIndex("FornecedorId", "InsumoId", "QuantidadeBase", "UnidadeBase")
                        .IsUnique();

                    b.ToTable("FornecedorProdutos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Oferta_Quantidade", "[QuantidadeEmbalagem] > 0 AND [QuantidadeBase] > 0");

                            t.HasCheckConstraint("CK_Oferta_Unidades", "[UnidadeEmbalagem] IN (1,2,3,4,5) AND [UnidadeBase] IN (1,2,3)");
                        });
                });

            modelBuilder.Entity("Perfumes.Api.Entities.FornecedorProdutoPreco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DataFim")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DataInicio")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("FornecedorProdutoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorProdutoId")
                        .IsUnique()
                        .HasFilter("[DataFim] IS NULL");

                    b.HasIndex("FornecedorProdutoId", "DataInicio")
                        .IsUnique();

                    b.ToTable("FornecedorProdutoPrecos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Preco_Valor", "[Preco] > 0");

                            t.HasCheckConstraint("CK_Preco_Vigencia", "[DataFim] IS NULL OR [DataFim] > [DataInicio]");
                        });
                });

            modelBuilder.Entity("Perfumes.Api.Entities.Insumo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("Densidade")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("TipoInsumo")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeMedida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("Insumos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Insumo_Densidade", "[Densidade] IS NULL OR [Densidade] > 0");

                            t.HasCheckConstraint("CK_Insumo_Tipo", "[TipoInsumo] IN (1,2)");

                            t.HasCheckConstraint("CK_Insumo_Unidade", "[UnidadeMedida] IN (1,2,3)");
                        });
                });

            modelBuilder.Entity("Perfumes.Api.Entities.FornecedorProduto", b =>
                {
                    b.HasOne("Perfumes.Api.Entities.Fornecedor", "Fornecedor")
                        .WithMany("Produtos")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Perfumes.Api.Entities.Insumo", "Insumo")
                        .WithMany("Ofertas")
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fornecedor");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("Perfumes.Api.Entities.FornecedorProdutoPreco", b =>
                {
                    b.HasOne("Perfumes.Api.Entities.FornecedorProduto", "FornecedorProduto")
                        .WithMany("Precos")
                        .HasForeignKey("FornecedorProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FornecedorProduto");
                });

            modelBuilder.Entity("Perfumes.Api.Entities.Fornecedor", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Perfumes.Api.Entities.FornecedorProduto", b =>
                {
                    b.Navigation("Precos");
                });

            modelBuilder.Entity("Perfumes.Api.Entities.Insumo", b =>
                {
                    b.Navigation("Ofertas");
                });
#pragma warning restore 612, 618
        }
    }
}
